[package]
name = "rlldp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
libc = "0.2.153"
thiserror = "1.0.58"
